[package]
name = "shared"
version = "0.1.0"
edition = "2021"
description = "Shared types and constants for Wira Desk"
license = "MIT"
repository = "https://github.com/kodesh87/wira-desk"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"


[lints]
workspace = true
